# Generated by Django 5.0.6 on 2025-05-17 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_favorites_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='created_by',
        ),
        migrations.AddField(
            model_name='gig',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='gig',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gig',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
